import time
print("Pyweek is ending in like 30 something hours.")
time.sleep(5)
print("I wanted to commit to this stuff every day. But I can't")
time.sleep(2)
print("I want to make a game tomorrow.")
time.sleep(2)
print("And I know for a fact that I will make it.")
time.sleep(1)
print("goodluck sarthak!")